import type { CatalogItemModel } from "./catalog_item_type";

export const products: CatalogItemModel[] = [
    {
        id: 1,
        name: 'Premium Wireless Headphones',
        description: 'High-quality wireless headphones with noise cancellation and 30-hour battery life.',
        price: 299.99,
        image: 'https://images.unsplash.com/photo-1713618651165-a3cf7f85506c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBoZWFkcGhvbmVzfGVufDF8fHx8MTc3NDk2MDI3M3ww&ixlib=rb-4.1.0&q=80&w=1080',
        category: 'Audio',
        rating: 4.5,
        reviews: 128,
        inStock: true,
    },
    {
        id: 2,
        name: 'True Wireless Earbuds',
        description: 'Compact and lightweight earbuds with crystal clear sound and touch controls.',
        price: 149.99,
        image: 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aXJlbGVzcyUyMGVhcmJ1ZHN8ZW58MXx8fHwxNzc0OTQyMTMyfDA&ixlib=rb-4.1.0&q=80&w=1080',
        category: 'Audio',
        rating: 4.7,
        reviews: 256,
        inStock: true,
    },
    {
        id: 3,
        name: 'Smart Watch Pro',
        description: 'Advanced smartwatch with fitness tracking, heart rate monitor, and GPS.',
        price: 399.99,
        image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbWFydCUyMHdhdGNofGVufDF8fHx8MTc3NDg5MTI1OHww&ixlib=rb-4.1.0&q=80&w=1080',
        category: 'Wearables',
        rating: 4.6,
        reviews: 184,
        inStock: true,
    },
    {
        id: 4,
        name: 'Ultra Laptop',
        description: 'Powerful laptop with 16GB RAM, 512GB SSD, and stunning 4K display.',
        price: 1299.99,
        image: 'https://images.unsplash.com/photo-1511385348-a52b4a160dc2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYXB0b3AlMjBjb21wdXRlcnxlbnwxfHx8fDE3NzQ5NzU0ODd8MA&ixlib=rb-4.1.0&q=80&w=1080',
        category: 'Computers',
        rating: 4.8,
        reviews: 312,
        inStock: true,
    },
    {
        id: 5,
        name: 'Professional Camera',
        description: 'Mirrorless camera with 24MP sensor and 4K video recording capabilities.',
        price: 1799.99,
        image: 'https://images.unsplash.com/photo-1579535984712-92fffbbaa266?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYW1lcmElMjBwaG90b2dyYXBoeXxlbnwxfHx8fDE3NzQ5MjE2MjR8MA&ixlib=rb-4.1.0&q=80&w=1080',
        category: 'Cameras',
        rating: 4.9,
        reviews: 89,
        inStock: true,
    },
    {
        id: 6,
        name: 'Premium Smartphone',
        description: 'Latest smartphone with 5G, triple camera system, and all-day battery.',
        price: 999.99,
        image: 'https://images.unsplash.com/photo-1741061961703-0739f3454314?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbWFydHBob25lJTIwbW9iaWxlfGVufDF8fHx8MTc3NDkzNzQ0N3ww&ixlib=rb-4.1.0&q=80&w=1080',
        category: 'Phones',
        rating: 4.7,
        reviews: 445,
        inStock: false,
    },
    {
        id: 7,
        name: 'Pro Tablet',
        description: '12.9-inch tablet with stylus support and powerful processor for creators.',
        price: 799.99,
        image: 'https://images.unsplash.com/photo-1769603795371-ad63bd85d524?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0YWJsZXQlMjBkZXZpY2V8ZW58MXx8fHwxNzc0OTc1NDkwfDA&ixlib=rb-4.1.0&q=80&w=1080',
        category: 'Tablets',
        rating: 4.6,
        reviews: 167,
        inStock: true,
    },
    {
        id: 8,
        name: 'Mechanical Gaming Keyboard',
        description: 'RGB mechanical keyboard with customizable keys and anti-ghosting technology.',
        price: 159.99,
        image: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnYW1pbmclMjBrZXlib2FyZHxlbnwxfHx8fDE3NzQ5ODA1MTJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
        category: 'Gaming',
        rating: 4.4,
        reviews: 203,
        inStock: true,
    },
];